// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4uOq3DBFo-FAbyytNWUzxSzSn3Kr2K7A',
    appId: '1:139519112315:web:eff126d0e2137916ba9ede',
    messagingSenderId: '139519112315',
    projectId: 'anotherwordgame-6b475',
    authDomain: 'anotherwordgame-6b475.firebaseapp.com',
    storageBucket: 'anotherwordgame-6b475.appspot.com',
    measurementId: 'G-XZG6TC0ZR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWjccz52FoUrcofyzoTPCeRMyzOOPCGrE',
    appId: '1:139519112315:android:8afc31dae1ae1f9cba9ede',
    messagingSenderId: '139519112315',
    projectId: 'anotherwordgame-6b475',
    storageBucket: 'anotherwordgame-6b475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTz_5RnZTV76uhMrXft4onxFiFMCP0i3w',
    appId: '1:139519112315:ios:be19f673058b4391ba9ede',
    messagingSenderId: '139519112315',
    projectId: 'anotherwordgame-6b475',
    storageBucket: 'anotherwordgame-6b475.appspot.com',
    iosClientId: '139519112315-ua1859u2o84i5stu0o0j5o180phin77q.apps.googleusercontent.com',
    iosBundleId: 'another.word.anotherwordgame2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTz_5RnZTV76uhMrXft4onxFiFMCP0i3w',
    appId: '1:139519112315:ios:be19f673058b4391ba9ede',
    messagingSenderId: '139519112315',
    projectId: 'anotherwordgame-6b475',
    storageBucket: 'anotherwordgame-6b475.appspot.com',
    iosClientId: '139519112315-ua1859u2o84i5stu0o0j5o180phin77q.apps.googleusercontent.com',
    iosBundleId: 'another.word.anotherwordgame2',
  );
}
